"""Add importance and structured extraction fields to articles

Revision ID: b48c57e059d8
Revises: a29ea4e9f2b0
Create Date: 2026-03-01 15:36:33.994927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b48c57e059d8'
down_revision: Union[str, Sequence[str], None] = 'a29ea4e9f2b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('interest_score', sa.Float(), nullable=True))
    op.add_column('articles', sa.Column('importance_score', sa.Float(), nullable=True))
    op.add_column('articles', sa.Column('must_know_level', sa.Text(), nullable=True))
    op.add_column('articles', sa.Column('event_type', sa.Text(), nullable=True))
    op.add_column('articles', sa.Column('geo_scope', sa.Text(), nullable=True))
    op.add_column('articles', sa.Column('time_sensitivity', sa.Text(), nullable=True))
    op.add_column('articles', sa.Column('severity', sa.Text(), nullable=True))
    op.add_column('articles', sa.Column('personal_impact_flags', sa.Text(), nullable=True))
    op.add_column('articles', sa.Column('confirmed_sources', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'confirmed_sources')
    op.drop_column('articles', 'personal_impact_flags')
    op.drop_column('articles', 'severity')
    op.drop_column('articles', 'time_sensitivity')
    op.drop_column('articles', 'geo_scope')
    op.drop_column('articles', 'event_type')
    op.drop_column('articles', 'must_know_level')
    op.drop_column('articles', 'importance_score')
    op.drop_column('articles', 'interest_score')
    # ### end Alembic commands ###
